apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/authorization-authentification-backend: "true"
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/promtail/promtail.yml
          image: grafana/promtail:latest
          name: promtail
          volumeMounts:
            - mountPath: /promtail/promtail.yml
              name: promtail-claim0
            - mountPath: /var/lib/docker/containers
              name: promtail-claim1
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: promtail-claim2
      restartPolicy: Always
      volumes:
        - name: promtail-claim0
          persistentVolumeClaim:
            claimName: promtail-claim0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
            readOnly: true
        - name: promtail-claim2
          persistentVolumeClaim:
            claimName: promtail-claim2
