apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: redisinsight
  name: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisinsight
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/authorization-authentification-backend: "true"
        io.kompose.service: redisinsight
    spec:
      containers:
        - image: redis/redisinsight:latest
          name: redisinsight
          ports:
            - containerPort: 5540
              hostPort: 5540
              protocol: TCP
      restartPolicy: Always
